### ISSUE TITLE
Repeating Error when closing the open file dialog box

### ISSUE THREAD

**Issue by MikeCarlo** [PowerBISteve/HotSwapConnections#2]
When I open a dialog box to select a new file, If I hit cancel, the script gets stuck in an endless loop of error messages. 

![image](https://user-images.githubusercontent.com/25160592/94339219-d3784d80-ffbd-11ea-8c95-e20d8f72d963.png)

**Comment by PowerBISteve** [comment]
fixed in v 1.1
